---
title: "MAT 653: Statistical Simulation"
author:
  - Instructor$:$ Dr. Wei Li
  - Scribe$:$   Jianchen Wei
date: Oct 14th, 2021
geometry: left=2cm, right=2cm, top=2cm, bottom=2cm
linestretch: 1.3
output:
  pdf_document: 
      include:
        in_header: preamble_rmd.tex
  html_document:
    df_print: paged
  html_notebook: default
fontsize: 14pt
header-includes:
- \usepackage{amsmath}
- \usepackage[linewidth=1pt]{mdframed}
- \newcommand\inner[2]{\left\langle#1,#2\right\rangle}
- \newcommand\floor[1]{\lfloor#1\rfloor}
- \newcommand\ceil[1]{\lceil#1\rceil}
- \newcommand\mb[1]{\mathbf{#1}}
- \newcommand\bs[1]{\boldsymbol{#1}}
- \newcommand\mr[1]{\mathrm{#1}}
- \newcommand\wh[1]{\widehat{#1}}
- \newcommand\op[1]{\operatorname{#1}}
- \newcommand\mbb[1]{\mathbb{#1}}
- \usepackage{caption}
- \captionsetup[figure]{labelformat=empty}
- \newcommand{\wei}[1]{\textcolor{orange}{(Wei:#1)}}
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,eval=T)
```
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>


# Self-normalize Importance Sampling


**Target:** 
$E_f(h(x))$

$f\propto f_0$, $g$ is importance pdf, and $supp(f)\subset supp(g).$

Self-normalized importance sampling $\implies \big(x_i , \frac{f_0(x_i)}{g_0(x_i)}\big)$ importance sample. It turns out this can be recycled by multinomial resampling into a sample that is from $f$.

**Step 1:** 
Sample $x_i\sim g$, obtain $\big(x_i,\frac{f_0(x_i)}{g_0(x_i)}\big)_{i=1}^n$

**Step 2:**
importance weights $w_i = \frac{f_0(x_i)}{g_0(x_i)}$. Let $\hat{w_i}=\frac{\frac{1}{n}w_i}{\frac{1}{n}\sum_j^n w_j}$. Notice that $\hat{w_i}\in(0,1), \sum\hat{w_i}=1$

**Step 3:**
draw a random sample of size $m$ with replacement from $x_1,\cdots,x_n$ with weighted probabilities by $\hat{w_1},\cdots,\hat{w_n}$: that is for $k=1, 2, \ldots, m$,
\begin{equation*}
X^*_k= \left\{
\begin{aligned}
x_1 &\quad& \mbox{with prob}=\hat{w_1}\\
x_2 &\quad& \mbox{with prob}=\hat{w_2}\\
&\vdots&\\
x_n &\quad& \mbox{with prob}=\hat{w_n}
\end{aligned}
\right.
\end{equation*}
It turns out that $(X_1^*,X_2^*,\cdots,X_m^*)$ is a random sample from $f$.

Remark: for this sampling to work, the target sample size $m$ should be no more than $10\%$ of the original sample size $n$.






