---
title: "MAT 653: Statistical Simulation"
author: Instructor$:$ Dr. Wei Li
date: "`r Sys.Date()`"
geometry: left=2cm, right=2cm, top=2cm, bottom=2cm
linestretch: 1.3
output:
  html_document:
    df_print: paged
    mathjax_config:
      - TeX-AMS-MML_HTMLorMML   
  pdf_document: 
      include:
        in_header: preamble_rmd.tex
  html_notebook: default
fontsize: 14pt
header-includes:
- \usepackage{amsmath}
- \usepackage[linewidth=1pt]{mdframed}
- \newcommand\inner[2]{\left\langle#1,#2\right\rangle}
- \newcommand\floor[1]{\lfloor#1\rfloor}
- \newcommand\ceil[1]{\lceil#1\rceil}
- \newcommand\mb[1]{\mathbf{#1}}
- \newcommand\bs[1]{\boldsymbol{#1}}
- \newcommand\mr[1]{\mathrm{#1}}
- \newcommand\wh[1]{\widehat{#1}}
- \newcommand\op[1]{\operatorname{#1}}
- \newcommand\mbb[1]{\mathbb{#1}}
- \usepackage{caption}
- \captionsetup[figure]{labelformat=empty}
- \newcommand{\wei}[1]{\textcolor{orange}{(Wei:#1)}}
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,eval=T)
```
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>


<span style="background-color: #f5f5f5; padding: 5px; display: block;">
    <span style="width: 25%; display: inline-block; text-align: left;">
        [Back](javascript:window.history.back())
    </span>
    <span style="width: 30%; display: inline-block; text-align: center; color: grey;">
        **Updated:** `r Sys.Date()`
    </span>
    <span style="width: 35%; display: inline-block; text-align: right; color: grey;">
        Statistical Simulation, Wei Li
    </span>
</span>

<!------------->


# Eigenvalue decomposition

Square matrix $M$. $Mx=\lambda x$ for some nonzero vector $x$ and some $\lambda$(scalar).

We call $\lambda$ a eigenvalue of $M$ whose associated eigenvector is $x$.

Note: $A$ is a square matrix. $\det(A)=\prod_{i=1}^n \lambda_i$.

**Eigen-decomposition:** $A$ is a square and symmetric matrix. then $A=P \Lambda P^T$ where 
$$P=[u_1, u_2,\cdots, u_n], u\mbox{'s are the orthonormal eigenvector of }A$$
$$\Lambda = \{\mbox{diagonal entries are the eigenvalues of }A\}$$
Note: If this symmetric matrix $A$ is invertible, then $A^{-1}=P\Lambda^{-1}P^T$ where 
\begin{equation*}
\Lambda^{-1} = 
\begin{pmatrix}
\ddots & 0 & 0 \\
0 & \frac{1}{\lambda_i} & 0 \\
0 & 0 & \ddots
\end{pmatrix}
\end{equation*}

\begin{mdframed}
Example: $A=\begin{pmatrix}
 9 & 0 \\
0 & 4 
\end{pmatrix}$, $Av = \lambda v\implies (A-\lambda I)v=0$. Here we need a non-zero solution, so
$$
\det(A-\lambda I)=\left|
\begin{matrix} 
   9-\lambda & 0   \\
   0 & 4-\lambda
\end{matrix}
   \right| =0 \implies \lambda_1=9,\lambda_2=4
$$

For $\lambda_1=9$, since we know  $Av_1=9v_1\implies (A-9I)v_1=0$, then we have
$$
\begin{pmatrix} 
   0 & 0   \\
   0 & -5
\end{pmatrix} v_1 =
\begin{pmatrix} 
   0    \\
   0 
\end{pmatrix}
\implies v_1=\begin{pmatrix} 
   1   \\
   0
\end{pmatrix}
$$
For $\lambda_2=4$, since we know  $Av_2=4v_2\implies (A-4I)v_2=0$, then we have
$$
\begin{pmatrix} 
   5 & 0   \\
   0 & 0
\end{pmatrix} v_2 =
\begin{pmatrix} 
   0    \\
   0 
\end{pmatrix}
\implies v_2=\begin{pmatrix} 
   0   \\
   1 
\end{pmatrix}
$$
Now $A=P\Lambda P^T=
\begin{pmatrix} 
   1 & 0   \\
   0 & 1
\end{pmatrix}
\begin{pmatrix} 
   9 & 0   \\
   0 & 4
\end{pmatrix}
\begin{pmatrix} 
   1 & 0   \\
   0 & 1
\end{pmatrix}$ where $P=[v_1,v_2]$.
\end{mdframed}



<!------------->
<span style="background-color: #f5f5f5; padding: 5px; display: block;">
    <span style="width: 25%; display: inline-block; text-align: left;">
        [Back](javascript:window.history.back())
    </span>
    <span style="width: 30%; display: inline-block; text-align: center; color: grey;">
        **Updated:** `r Sys.Date()`
    </span>
    <span style="width: 35%; display: inline-block; text-align: right; color: grey;">
        Statistical Simulation, Wei Li
    </span>
</span>


